# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 292)
        MainWindow.setMinimumSize(QtCore.QSize(436, 292))
        MainWindow.setMaximumSize(QtCore.QSize(436, 292))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textbox_url = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textbox_url.setObjectName("textbox_url")
        self.horizontalLayout.addWidget(self.textbox_url)
        self.textbox_start = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textbox_start.setObjectName("textbox_start")
        self.horizontalLayout.addWidget(self.textbox_start)
        self.textbox_end = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textbox_end.setObjectName("textbox_end")
        self.horizontalLayout.addWidget(self.textbox_end)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textbox_filename = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textbox_filename.setObjectName("textbox_filename")
        self.horizontalLayout_2.addWidget(self.textbox_filename)
        self.button_download = QtWidgets.QPushButton(self.centralwidget)
        self.button_download.setObjectName("button_download")
        self.horizontalLayout_2.addWidget(self.button_download)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_deletevid = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_deletevid.setObjectName("checkBox_deletevid")
        self.horizontalLayout_3.addWidget(self.checkBox_deletevid)
        self.textBrowser_Output = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Output.setObjectName("textBrowser_Output")
        self.horizontalLayout_3.addWidget(self.textBrowser_Output)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YoutubeDownloader für Neger"))
        self.textbox_url.setPlainText(_translate("MainWindow", ""))
        self.textbox_start.setPlainText(_translate("MainWindow", ""))
        self.textbox_end.setPlainText(_translate("MainWindow", ""))
        self.textbox_filename.setPlainText(_translate("MainWindow", ""))
        self.button_download.setText(_translate("MainWindow", "Clip runterladen"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Feld 1: URL</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Feld 2: Startzeit (optional)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Feld 3: Endzeit (optional)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Feld 4: Dateiname (optional)</p></body></html>"))
        self.checkBox_deletevid.setText(_translate("MainWindow", "Quellvideo löschen"))
